package br.com.fiap.techchallenge.processor.domain;

public enum DocumentType {
    EXAME_BETA_HCG,
    EXAME_OUTROS,
    EXAME_GLICEMIA_JEJUM,
    EXAME_HEMOGLOBINA_GLICADA,
    EXAME_HEMOGRAMA,
    EXAME_LIPIDOGRAMA,
    EXAME_T4_LIVRE,
    EXAME_TSH,

    LAUDO_COLONOSCOPIA,
    LAUDO_ENDOSCOPIA_DIGESTIVA_ALTA,
    LAUDO_MAMOGRAFIA,
    LAUDO_OUTROS,
    LAUDO_RESSONANCIA_MAGNETICA,
    LAUDO_TOMOGRAFIA_COMPUTADORIZADA,
    LAUDO_US_OBSTETRICO_DOPPLER,
    LAUDO_US_OBSTETRICO_ENDOVAGINAL,
    LAUDO_US_PELVICA_TRANSVAGINAL,
    LAUDO_UST_ABDOME_TOTAL,

    ENCAMINHAMENTO,
    OUTROS,
    RECEITA,
    REGISTRO_ATENDIMENTO,
    RELATORIO
}
